//All the words are in an array.

function randomWord() {
  var Words = [
    "car",
    "bus",
    "boat",
    "train",
    "tv",
    "railway",
    "computer",
    "toothbrush",
    "toothpaste",
    "cinder",
    "pot",
    "carwash",
    "sea",
    "ocean",
    "cyber",
    "ascii",
    "sci-fi",
    "rigged",
    "eyesight",
    "uranium",
    "block",
    "road",
    "radiator",
    "you found the secret word...?",
    "hanger",
    "dry",
    "clean",
    "curtains",
    "water",
    "holder",
    "cup",
    "greetings",
    "tree",
    "tomato",
    "plant",
    "grass",
    "wire",
    "sun",
    "earth",
    "moon",
    "school",
    "monster",
    "anger",
    "fear",
    "letter",
    "post",
    "country",
    "universe",
    "space",
    "anchor",
    "island",
    "continent",
    "bird",
    "clock",
    "boy",
    "plastic",
    "duck",
    "teacher",
    "old lady",
    "professor",
    "hamster",
    "get",
    "let",
    "constant",
    "concentrate",
    "amazing"
  ];

  const wordIndex = Words[Math.floor(Math.random() * Words.length).toString()];
  document.getElementById("randomword").innerHTML = wordIndex;

}
